# coding: utf-8

"""
    Pietsmiet.de API

    OpenAPI spec generated from HAR data for www.pietsmiet.de on 2024-09-03T03:22:16.459Z  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.any_of_variation1_url import AnyOfVariation1Url  # noqa: E501
from swagger_client.rest import ApiException


class TestAnyOfVariation1Url(unittest.TestCase):
    """AnyOfVariation1Url unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnyOfVariation1Url(self):
        """Test AnyOfVariation1Url"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.any_of_variation1_url.AnyOfVariation1Url()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
