# coding: utf-8

"""
    Pietsmiet.de API

    OpenAPI spec generated from HAR data for www.pietsmiet.de on 2024-09-03T03:22:16.459Z  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.any_of_datum7_followings_count import AnyOfDatum7FollowingsCount  # noqa: E501
from swagger_client.rest import ApiException


class TestAnyOfDatum7FollowingsCount(unittest.TestCase):
    """AnyOfDatum7FollowingsCount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnyOfDatum7FollowingsCount(self):
        """Test AnyOfDatum7FollowingsCount"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.any_of_datum7_followings_count.AnyOfDatum7FollowingsCount()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
