# coding: utf-8

"""
    Pietsmiet.de API

    OpenAPI spec generated from HAR data for www.pietsmiet.de on 2024-09-03T03:22:16.459Z  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.videos_playlists_id_post_request1 import VideosPlaylistsIDPostRequest1  # noqa: E501
from swagger_client.rest import ApiException


class TestVideosPlaylistsIDPostRequest1(unittest.TestCase):
    """VideosPlaylistsIDPostRequest1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVideosPlaylistsIDPostRequest1(self):
        """Test VideosPlaylistsIDPostRequest1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.videos_playlists_id_post_request1.VideosPlaylistsIDPostRequest1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
