# coding: utf-8

"""
    Pietsmiet.de API

    OpenAPI spec generated from HAR data for www.pietsmiet.de on 2024-09-03T03:22:16.459Z  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.ated_at import AtedAt  # noqa: E501
from swagger_client.rest import ApiException


class TestAtedAt(unittest.TestCase):
    """AtedAt unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAtedAt(self):
        """Test AtedAt"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.ated_at.AtedAt()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
