# coding: utf-8

"""
    Pietsmiet.de API

    OpenAPI spec generated from HAR data for www.pietsmiet.de on 2024-09-03T03:22:16.459Z  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.utility_api import UtilityApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUtilityApi(unittest.TestCase):
    """UtilityApi unit test stubs"""

    def setUp(self):
        self.api = UtilityApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_utility_follows(self):
        """Test case for delete_utility_follows

        Delete Utility Follows  # noqa: E501
        """
        pass

    def test_get_utility_comments(self):
        """Test case for get_utility_comments

        Get Utility Comments  # noqa: E501
        """
        pass

    def test_get_utility_follows(self):
        """Test case for get_utility_follows

        Get Utility Follows  # noqa: E501
        """
        pass

    def test_get_utility_player(self):
        """Test case for get_utility_player

        Get Utility Player  # noqa: E501
        """
        pass

    def test_post_utility_autobahn(self):
        """Test case for post_utility_autobahn

        Post Utility Autobahn  # noqa: E501
        """
        pass

    def test_post_utility_comments(self):
        """Test case for post_utility_comments

        Post Utility Comments  # noqa: E501
        """
        pass

    def test_post_utility_comments_by_id_reports(self):
        """Test case for post_utility_comments_by_id_reports

        Post Utility Comments By ID Reports  # noqa: E501
        """
        pass

    def test_post_utility_follows(self):
        """Test case for post_utility_follows

        Post Utility Follows  # noqa: E501
        """
        pass

    def test_post_utility_highlights(self):
        """Test case for post_utility_highlights

        Post Utility Highlights  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
