# coding: utf-8

"""
    Pietsmiet.de API

    OpenAPI spec generated from HAR data for www.pietsmiet.de on 2024-09-03T03:22:16.459Z  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.any_of_datum13_participant_lineup import AnyOfDatum13ParticipantLineup  # noqa: E501
from swagger_client.rest import ApiException


class TestAnyOfDatum13ParticipantLineup(unittest.TestCase):
    """AnyOfDatum13ParticipantLineup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnyOfDatum13ParticipantLineup(self):
        """Test AnyOfDatum13ParticipantLineup"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.any_of_datum13_participant_lineup.AnyOfDatum13ParticipantLineup()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
