# coding: utf-8

"""
    Pietsmiet.de API

    OpenAPI spec generated from HAR data for www.pietsmiet.de on 2024-09-03T03:22:16.459Z  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.videos_api import VideosApi  # noqa: E501
from swagger_client.rest import ApiException


class TestVideosApi(unittest.TestCase):
    """VideosApi unit test stubs"""

    def setUp(self):
        self.api = VideosApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_channel_video_count(self):
        """Test case for get_channel_video_count

        Get Channel Video Count  # noqa: E501
        """
        pass

    def test_get_videos(self):
        """Test case for get_videos

        Get Videos  # noqa: E501
        """
        pass

    def test_get_videos_authors(self):
        """Test case for get_videos_authors

        Get Videos Authors  # noqa: E501
        """
        pass

    def test_get_videos_by_id(self):
        """Test case for get_videos_by_id

        Get Videos By ID  # noqa: E501
        """
        pass

    def test_get_videos_by_id_next(self):
        """Test case for get_videos_by_id_next

        Get Videos By ID Next  # noqa: E501
        """
        pass

    def test_get_videos_channels(self):
        """Test case for get_videos_channels

        Get Videos Channels  # noqa: E501
        """
        pass

    def test_get_videos_clips(self):
        """Test case for get_videos_clips

        Get Videos Clips  # noqa: E501
        """
        pass

    def test_get_videos_playlists(self):
        """Test case for get_videos_playlists

        Get Videos Playlists  # noqa: E501
        """
        pass

    def test_get_videos_playlists_by_id(self):
        """Test case for get_videos_playlists_by_id

        Get Videos Playlists By ID  # noqa: E501
        """
        pass

    def test_post_videos_clips(self):
        """Test case for post_videos_clips

        Post Videos Clips  # noqa: E501
        """
        pass

    def test_post_videos_playlists_by_id(self):
        """Test case for post_videos_playlists_by_id

        Post Videos Playlists By ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
