# coding: utf-8

"""
    Pietsmiet.de API

    OpenAPI spec generated from HAR data for www.pietsmiet.de on 2024-09-03T03:22:16.459Z  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.polls_api import PollsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPollsApi(unittest.TestCase):
    """PollsApi unit test stubs"""

    def setUp(self):
        self.api = PollsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_polls(self):
        """Test case for get_polls

        Get Polls  # noqa: E501
        """
        pass

    def test_get_polls_votes(self):
        """Test case for get_polls_votes

        Get Polls Votes  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
