# coding: utf-8

"""
    Pietsmiet.de API

    OpenAPI spec generated from HAR data for www.pietsmiet.de on 2024-09-03T03:22:16.459Z  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.users_api import UsersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_users_by_id_tokens_id(self):
        """Test case for delete_users_by_id_tokens_id

        Delete Tokens by User Id  # noqa: E501
        """
        pass

    def test_delete_users_object20_object_tokens(self):
        """Test case for delete_users_object20_object_tokens

        Delete Users Object 20 Object Tokens  # noqa: E501
        """
        pass

    def test_get_users_by_id(self):
        """Test case for get_users_by_id

        Get Users By ID  # noqa: E501
        """
        pass

    def test_get_users_by_id_achievements(self):
        """Test case for get_users_by_id_achievements

        Get Users By ID Achievements  # noqa: E501
        """
        pass

    def test_get_users_by_id_dislikes(self):
        """Test case for get_users_by_id_dislikes

        Get Users By ID Dislikes  # noqa: E501
        """
        pass

    def test_get_users_by_id_followings(self):
        """Test case for get_users_by_id_followings

        Get Users By ID Followings  # noqa: E501
        """
        pass

    def test_get_users_by_id_invoices(self):
        """Test case for get_users_by_id_invoices

        Get Users By ID Invoices  # noqa: E501
        """
        pass

    def test_get_users_by_id_likes(self):
        """Test case for get_users_by_id_likes

        Get Users By ID Likes  # noqa: E501
        """
        pass

    def test_get_users_by_id_notifications(self):
        """Test case for get_users_by_id_notifications

        Get Users By ID Notifications  # noqa: E501
        """
        pass

    def test_get_users_by_id_settings_notifications(self):
        """Test case for get_users_by_id_settings_notifications

        Get Users By ID Settings Notifications  # noqa: E501
        """
        pass

    def test_get_users_by_id_settings_twofactor_setup(self):
        """Test case for get_users_by_id_settings_twofactor_setup

        Get Users By ID Settings Twofactor Setup  # noqa: E501
        """
        pass

    def test_get_users_by_id_subscriptions(self):
        """Test case for get_users_by_id_subscriptions

        Get Users By ID Subscriptions  # noqa: E501
        """
        pass

    def test_get_users_by_id_tokens(self):
        """Test case for get_users_by_id_tokens

        Get Users By ID Tokens  # noqa: E501
        """
        pass

    def test_get_users_by_id_views(self):
        """Test case for get_users_by_id_views

        Get Users By ID Views  # noqa: E501
        """
        pass

    def test_get_users_me(self):
        """Test case for get_users_me

        Get Users Me  # noqa: E501
        """
        pass

    def test_patch_users_by_id_notifications_by_uuid(self):
        """Test case for patch_users_by_id_notifications_by_uuid

        Patch Users By ID Notifications By UUID  # noqa: E501
        """
        pass

    def test_patch_users_by_id_settings_notifications(self):
        """Test case for patch_users_by_id_settings_notifications

        Patch Users By ID Settings Notifications  # noqa: E501
        """
        pass

    def test_patch_users_by_id_settings_password(self):
        """Test case for patch_users_by_id_settings_password

        Patch Users By ID Settings Password  # noqa: E501
        """
        pass

    def test_patch_users_by_id_settings_preferences(self):
        """Test case for patch_users_by_id_settings_preferences

        Patch Users By ID Settings Preferences  # noqa: E501
        """
        pass

    def test_patch_users_by_id_settings_profile(self):
        """Test case for patch_users_by_id_settings_profile

        Patch Users By ID Settings Profile  # noqa: E501
        """
        pass

    def test_post_users_by_id_dislikes(self):
        """Test case for post_users_by_id_dislikes

        Post Users By ID Dislikes  # noqa: E501
        """
        pass

    def test_post_users_by_id_likes(self):
        """Test case for post_users_by_id_likes

        Post Users By ID Likes  # noqa: E501
        """
        pass

    def test_post_users_by_id_settings_assets(self):
        """Test case for post_users_by_id_settings_assets

        Post Users By ID Settings Assets  # noqa: E501
        """
        pass

    def test_post_users_by_id_settings_data_request(self):
        """Test case for post_users_by_id_settings_data_request

        Post Users By ID Settings Data Request  # noqa: E501
        """
        pass

    def test_post_users_by_id_settings_twofactor_reset(self):
        """Test case for post_users_by_id_settings_twofactor_reset

        Post Users By ID Settings Twofactor Reset  # noqa: E501
        """
        pass

    def test_post_users_by_id_settings_twofactor_setup(self):
        """Test case for post_users_by_id_settings_twofactor_setup

        Post Users By ID Settings Twofactor Setup  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
