# coding: utf-8

"""
    Pietsmiet.de API

    OpenAPI spec generated from HAR data for www.pietsmiet.de on 2024-09-03T03:22:16.459Z  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.news_api import NewsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestNewsApi(unittest.TestCase):
    """NewsApi unit test stubs"""

    def setUp(self):
        self.api = NewsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_news_articles(self):
        """Test case for get_news_articles

        Get News Articles  # noqa: E501
        """
        pass

    def test_get_news_articles_by_id(self):
        """Test case for get_news_articles_by_id

        Get News Articles By ID  # noqa: E501
        """
        pass

    def test_get_news_categories_id(self):
        """Test case for get_news_categories_id

        Get News Categories 34  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
