# coding: utf-8

"""
    Pietsmiet.de API

    OpenAPI spec generated from HAR data for www.pietsmiet.de on 2024-09-03T03:22:16.459Z  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AuthorPreferences(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'public_profile': 'bool',
        'subscription_enable_identification': 'bool'
    }

    attribute_map = {
        'public_profile': 'public_profile',
        'subscription_enable_identification': 'subscription_enable_identification'
    }

    def __init__(self, public_profile=None, subscription_enable_identification=None):  # noqa: E501
        """AuthorPreferences - a model defined in Swagger"""  # noqa: E501
        self._public_profile = None
        self._subscription_enable_identification = None
        self.discriminator = None
        if public_profile is not None:
            self.public_profile = public_profile
        if subscription_enable_identification is not None:
            self.subscription_enable_identification = subscription_enable_identification

    @property
    def public_profile(self):
        """Gets the public_profile of this AuthorPreferences.  # noqa: E501


        :return: The public_profile of this AuthorPreferences.  # noqa: E501
        :rtype: bool
        """
        return self._public_profile

    @public_profile.setter
    def public_profile(self, public_profile):
        """Sets the public_profile of this AuthorPreferences.


        :param public_profile: The public_profile of this AuthorPreferences.  # noqa: E501
        :type: bool
        """

        self._public_profile = public_profile

    @property
    def subscription_enable_identification(self):
        """Gets the subscription_enable_identification of this AuthorPreferences.  # noqa: E501


        :return: The subscription_enable_identification of this AuthorPreferences.  # noqa: E501
        :rtype: bool
        """
        return self._subscription_enable_identification

    @subscription_enable_identification.setter
    def subscription_enable_identification(self, subscription_enable_identification):
        """Sets the subscription_enable_identification of this AuthorPreferences.


        :param subscription_enable_identification: The subscription_enable_identification of this AuthorPreferences.  # noqa: E501
        :type: bool
        """

        self._subscription_enable_identification = subscription_enable_identification

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AuthorPreferences, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AuthorPreferences):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
