# coding: utf-8

"""
    Pietsmiet.de API

    OpenAPI spec generated from HAR data for www.pietsmiet.de on 2024-09-03T03:22:16.459Z  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Channels(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'via_mail': 'bool',
        'via_website': 'bool'
    }

    attribute_map = {
        'via_mail': 'via_mail',
        'via_website': 'via_website'
    }

    def __init__(self, via_mail=None, via_website=None):  # noqa: E501
        """Channels - a model defined in Swagger"""  # noqa: E501
        self._via_mail = None
        self._via_website = None
        self.discriminator = None
        if via_mail is not None:
            self.via_mail = via_mail
        if via_website is not None:
            self.via_website = via_website

    @property
    def via_mail(self):
        """Gets the via_mail of this Channels.  # noqa: E501


        :return: The via_mail of this Channels.  # noqa: E501
        :rtype: bool
        """
        return self._via_mail

    @via_mail.setter
    def via_mail(self, via_mail):
        """Sets the via_mail of this Channels.


        :param via_mail: The via_mail of this Channels.  # noqa: E501
        :type: bool
        """

        self._via_mail = via_mail

    @property
    def via_website(self):
        """Gets the via_website of this Channels.  # noqa: E501


        :return: The via_website of this Channels.  # noqa: E501
        :rtype: bool
        """
        return self._via_website

    @via_website.setter
    def via_website(self, via_website):
        """Sets the via_website of this Channels.


        :param via_website: The via_website of this Channels.  # noqa: E501
        :type: bool
        """

        self._via_website = via_website

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Channels, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Channels):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
