# coding: utf-8

"""
    Pietsmiet.de API

    OpenAPI spec generated from HAR data for www.pietsmiet.de on 2024-09-03T03:22:16.459Z  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConfigOriginIntegrityHeader(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'h': 'str',
        'v': 'str'
    }

    attribute_map = {
        'h': 'h',
        'v': 'v'
    }

    def __init__(self, h=None, v=None):  # noqa: E501
        """ConfigOriginIntegrityHeader - a model defined in Swagger"""  # noqa: E501
        self._h = None
        self._v = None
        self.discriminator = None
        if h is not None:
            self.h = h
        if v is not None:
            self.v = v

    @property
    def h(self):
        """Gets the h of this ConfigOriginIntegrityHeader.  # noqa: E501

        Base64 Encoded X-Origin-Integrity Header Name  # noqa: E501

        :return: The h of this ConfigOriginIntegrityHeader.  # noqa: E501
        :rtype: str
        """
        return self._h

    @h.setter
    def h(self, h):
        """Sets the h of this ConfigOriginIntegrityHeader.

        Base64 Encoded X-Origin-Integrity Header Name  # noqa: E501

        :param h: The h of this ConfigOriginIntegrityHeader.  # noqa: E501
        :type: str
        """
        allowed_values = ["X-Origin-Integrity", "WC1PcmlnaW4tSW50ZWdyaXR5"]  # noqa: E501
        if h not in allowed_values:
            raise ValueError(
                "Invalid value for `h` ({0}), must be one of {1}"  # noqa: E501
                .format(h, allowed_values)
            )

        self._h = h

    @property
    def v(self):
        """Gets the v of this ConfigOriginIntegrityHeader.  # noqa: E501

        Base64 Encoded X-Origin-Integrity Header Value  # noqa: E501

        :return: The v of this ConfigOriginIntegrityHeader.  # noqa: E501
        :rtype: str
        """
        return self._v

    @v.setter
    def v(self, v):
        """Sets the v of this ConfigOriginIntegrityHeader.

        Base64 Encoded X-Origin-Integrity Header Value  # noqa: E501

        :param v: The v of this ConfigOriginIntegrityHeader.  # noqa: E501
        :type: str
        """

        self._v = v

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConfigOriginIntegrityHeader, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConfigOriginIntegrityHeader):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
