# coding: utf-8

"""
    Pietsmiet.de API

    OpenAPI spec generated from HAR data for www.pietsmiet.de on 2024-09-03T03:22:16.459Z  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Dash(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'labels': 'list[str]',
        'labels_bitrate': 'dict(str, str)',
        'src': 'str',
        'type': 'str'
    }

    attribute_map = {
        'labels': 'labels',
        'labels_bitrate': 'labels_bitrate',
        'src': 'src',
        'type': 'type'
    }

    def __init__(self, labels=None, labels_bitrate=None, src=None, type=None):  # noqa: E501
        """Dash - a model defined in Swagger"""  # noqa: E501
        self._labels = None
        self._labels_bitrate = None
        self._src = None
        self._type = None
        self.discriminator = None
        if labels is not None:
            self.labels = labels
        if labels_bitrate is not None:
            self.labels_bitrate = labels_bitrate
        if src is not None:
            self.src = src
        if type is not None:
            self.type = type

    @property
    def labels(self):
        """Gets the labels of this Dash.  # noqa: E501


        :return: The labels of this Dash.  # noqa: E501
        :rtype: list[str]
        """
        return self._labels

    @labels.setter
    def labels(self, labels):
        """Sets the labels of this Dash.


        :param labels: The labels of this Dash.  # noqa: E501
        :type: list[str]
        """

        self._labels = labels

    @property
    def labels_bitrate(self):
        """Gets the labels_bitrate of this Dash.  # noqa: E501


        :return: The labels_bitrate of this Dash.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._labels_bitrate

    @labels_bitrate.setter
    def labels_bitrate(self, labels_bitrate):
        """Sets the labels_bitrate of this Dash.


        :param labels_bitrate: The labels_bitrate of this Dash.  # noqa: E501
        :type: dict(str, str)
        """

        self._labels_bitrate = labels_bitrate

    @property
    def src(self):
        """Gets the src of this Dash.  # noqa: E501


        :return: The src of this Dash.  # noqa: E501
        :rtype: str
        """
        return self._src

    @src.setter
    def src(self, src):
        """Sets the src of this Dash.


        :param src: The src of this Dash.  # noqa: E501
        :type: str
        """

        self._src = src

    @property
    def type(self):
        """Gets the type of this Dash.  # noqa: E501


        :return: The type of this Dash.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Dash.


        :param type: The type of this Dash.  # noqa: E501
        :type: str
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Dash, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Dash):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
