# coding: utf-8

"""
    Pietsmiet.de API

    OpenAPI spec generated from HAR data for www.pietsmiet.de on 2024-09-03T03:22:16.459Z  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Data(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'notifications': 'int',
        'actions': 'list[Action]',
        'icon': 'str',
        'text': 'str'
    }

    attribute_map = {
        'notifications': '_notifications',
        'actions': 'actions',
        'icon': 'icon',
        'text': 'text'
    }

    def __init__(self, notifications=None, actions=None, icon=None, text=None):  # noqa: E501
        """Data - a model defined in Swagger"""  # noqa: E501
        self._notifications = None
        self._actions = None
        self._icon = None
        self._text = None
        self.discriminator = None
        if notifications is not None:
            self.notifications = notifications
        if actions is not None:
            self.actions = actions
        if icon is not None:
            self.icon = icon
        if text is not None:
            self.text = text

    @property
    def notifications(self):
        """Gets the notifications of this Data.  # noqa: E501


        :return: The notifications of this Data.  # noqa: E501
        :rtype: int
        """
        return self._notifications

    @notifications.setter
    def notifications(self, notifications):
        """Sets the notifications of this Data.


        :param notifications: The notifications of this Data.  # noqa: E501
        :type: int
        """

        self._notifications = notifications

    @property
    def actions(self):
        """Gets the actions of this Data.  # noqa: E501


        :return: The actions of this Data.  # noqa: E501
        :rtype: list[Action]
        """
        return self._actions

    @actions.setter
    def actions(self, actions):
        """Sets the actions of this Data.


        :param actions: The actions of this Data.  # noqa: E501
        :type: list[Action]
        """

        self._actions = actions

    @property
    def icon(self):
        """Gets the icon of this Data.  # noqa: E501


        :return: The icon of this Data.  # noqa: E501
        :rtype: str
        """
        return self._icon

    @icon.setter
    def icon(self, icon):
        """Sets the icon of this Data.


        :param icon: The icon of this Data.  # noqa: E501
        :type: str
        """

        self._icon = icon

    @property
    def text(self):
        """Gets the text of this Data.  # noqa: E501


        :return: The text of this Data.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this Data.


        :param text: The text of this Data.  # noqa: E501
        :type: str
        """

        self._text = text

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Data, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Data):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
