# coding: utf-8

"""
    Pietsmiet.de API

    OpenAPI spec generated from HAR data for www.pietsmiet.de on 2024-09-03T03:22:16.459Z  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Datum17(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'created_at': 'datetime',
        'id': 'int',
        'object_id': 'int',
        'object_type': 'str',
        'timestamp': 'int',
        'timestamp_pretty': 'str',
        'updated_at': 'datetime',
        'user_id': 'int'
    }

    attribute_map = {
        'created_at': 'created_at',
        'id': 'id',
        'object_id': 'object_id',
        'object_type': 'object_type',
        'timestamp': 'timestamp',
        'timestamp_pretty': 'timestamp_pretty',
        'updated_at': 'updated_at',
        'user_id': 'user_id'
    }

    def __init__(self, created_at=None, id=None, object_id=None, object_type=None, timestamp=None, timestamp_pretty=None, updated_at=None, user_id=None):  # noqa: E501
        """Datum17 - a model defined in Swagger"""  # noqa: E501
        self._created_at = None
        self._id = None
        self._object_id = None
        self._object_type = None
        self._timestamp = None
        self._timestamp_pretty = None
        self._updated_at = None
        self._user_id = None
        self.discriminator = None
        if created_at is not None:
            self.created_at = created_at
        if id is not None:
            self.id = id
        if object_id is not None:
            self.object_id = object_id
        if object_type is not None:
            self.object_type = object_type
        if timestamp is not None:
            self.timestamp = timestamp
        if timestamp_pretty is not None:
            self.timestamp_pretty = timestamp_pretty
        if updated_at is not None:
            self.updated_at = updated_at
        if user_id is not None:
            self.user_id = user_id

    @property
    def created_at(self):
        """Gets the created_at of this Datum17.  # noqa: E501


        :return: The created_at of this Datum17.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this Datum17.


        :param created_at: The created_at of this Datum17.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def id(self):
        """Gets the id of this Datum17.  # noqa: E501


        :return: The id of this Datum17.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Datum17.


        :param id: The id of this Datum17.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def object_id(self):
        """Gets the object_id of this Datum17.  # noqa: E501


        :return: The object_id of this Datum17.  # noqa: E501
        :rtype: int
        """
        return self._object_id

    @object_id.setter
    def object_id(self, object_id):
        """Sets the object_id of this Datum17.


        :param object_id: The object_id of this Datum17.  # noqa: E501
        :type: int
        """

        self._object_id = object_id

    @property
    def object_type(self):
        """Gets the object_type of this Datum17.  # noqa: E501


        :return: The object_type of this Datum17.  # noqa: E501
        :rtype: str
        """
        return self._object_type

    @object_type.setter
    def object_type(self, object_type):
        """Sets the object_type of this Datum17.


        :param object_type: The object_type of this Datum17.  # noqa: E501
        :type: str
        """
        allowed_values = ["video", "podcastEpisode"]  # noqa: E501
        if object_type not in allowed_values:
            raise ValueError(
                "Invalid value for `object_type` ({0}), must be one of {1}"  # noqa: E501
                .format(object_type, allowed_values)
            )

        self._object_type = object_type

    @property
    def timestamp(self):
        """Gets the timestamp of this Datum17.  # noqa: E501


        :return: The timestamp of this Datum17.  # noqa: E501
        :rtype: int
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this Datum17.


        :param timestamp: The timestamp of this Datum17.  # noqa: E501
        :type: int
        """

        self._timestamp = timestamp

    @property
    def timestamp_pretty(self):
        """Gets the timestamp_pretty of this Datum17.  # noqa: E501


        :return: The timestamp_pretty of this Datum17.  # noqa: E501
        :rtype: str
        """
        return self._timestamp_pretty

    @timestamp_pretty.setter
    def timestamp_pretty(self, timestamp_pretty):
        """Sets the timestamp_pretty of this Datum17.


        :param timestamp_pretty: The timestamp_pretty of this Datum17.  # noqa: E501
        :type: str
        """

        self._timestamp_pretty = timestamp_pretty

    @property
    def updated_at(self):
        """Gets the updated_at of this Datum17.  # noqa: E501


        :return: The updated_at of this Datum17.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this Datum17.


        :param updated_at: The updated_at of this Datum17.  # noqa: E501
        :type: datetime
        """

        self._updated_at = updated_at

    @property
    def user_id(self):
        """Gets the user_id of this Datum17.  # noqa: E501


        :return: The user_id of this Datum17.  # noqa: E501
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this Datum17.


        :param user_id: The user_id of this Datum17.  # noqa: E501
        :type: int
        """

        self._user_id = user_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Datum17, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Datum17):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
