# coding: utf-8

"""
    Pietsmiet.de API

    OpenAPI spec generated from HAR data for www.pietsmiet.de on 2024-09-03T03:22:16.459Z  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Datum15(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ad': 'bool',
        'id': 'AnyOfDatum15Id',
        'publish_date': 'AnyOfDatum15PublishDate',
        'title': 'str',
        'type': 'AnyOfDatum15Type',
        'url': 'str'
    }

    attribute_map = {
        'ad': 'ad',
        'id': 'id',
        'publish_date': 'publish_date',
        'title': 'title',
        'type': 'type',
        'url': 'url'
    }

    def __init__(self, ad=None, id=None, publish_date=None, title=None, type=None, url=None):  # noqa: E501
        """Datum15 - a model defined in Swagger"""  # noqa: E501
        self._ad = None
        self._id = None
        self._publish_date = None
        self._title = None
        self._type = None
        self._url = None
        self.discriminator = None
        if ad is not None:
            self.ad = ad
        if id is not None:
            self.id = id
        if publish_date is not None:
            self.publish_date = publish_date
        if title is not None:
            self.title = title
        if type is not None:
            self.type = type
        if url is not None:
            self.url = url

    @property
    def ad(self):
        """Gets the ad of this Datum15.  # noqa: E501


        :return: The ad of this Datum15.  # noqa: E501
        :rtype: bool
        """
        return self._ad

    @ad.setter
    def ad(self, ad):
        """Sets the ad of this Datum15.


        :param ad: The ad of this Datum15.  # noqa: E501
        :type: bool
        """

        self._ad = ad

    @property
    def id(self):
        """Gets the id of this Datum15.  # noqa: E501


        :return: The id of this Datum15.  # noqa: E501
        :rtype: AnyOfDatum15Id
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Datum15.


        :param id: The id of this Datum15.  # noqa: E501
        :type: AnyOfDatum15Id
        """

        self._id = id

    @property
    def publish_date(self):
        """Gets the publish_date of this Datum15.  # noqa: E501


        :return: The publish_date of this Datum15.  # noqa: E501
        :rtype: AnyOfDatum15PublishDate
        """
        return self._publish_date

    @publish_date.setter
    def publish_date(self, publish_date):
        """Sets the publish_date of this Datum15.


        :param publish_date: The publish_date of this Datum15.  # noqa: E501
        :type: AnyOfDatum15PublishDate
        """

        self._publish_date = publish_date

    @property
    def title(self):
        """Gets the title of this Datum15.  # noqa: E501


        :return: The title of this Datum15.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this Datum15.


        :param title: The title of this Datum15.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def type(self):
        """Gets the type of this Datum15.  # noqa: E501


        :return: The type of this Datum15.  # noqa: E501
        :rtype: AnyOfDatum15Type
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Datum15.


        :param type: The type of this Datum15.  # noqa: E501
        :type: AnyOfDatum15Type
        """

        self._type = type

    @property
    def url(self):
        """Gets the url of this Datum15.  # noqa: E501


        :return: The url of this Datum15.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this Datum15.


        :param url: The url of this Datum15.  # noqa: E501
        :type: str
        """

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Datum15, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Datum15):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
