# coding: utf-8

"""
    Pietsmiet.de API

    OpenAPI spec generated from HAR data for www.pietsmiet.de on 2024-09-03T03:22:16.459Z  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LatestPlaylist(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'channel': 'Channel',
        'description': 'object',
        'first_video': 'FirstVideo',
        'followings_count': 'int',
        'id': 'int',
        'meta_tags': 'object',
        'publish_date': 'datetime',
        'slug': 'str',
        'title': 'str',
        'type': 'int',
        'url_slug': 'str',
        'videos_count': 'int'
    }

    attribute_map = {
        'channel': 'channel',
        'description': 'description',
        'first_video': 'first_video',
        'followings_count': 'followings_count',
        'id': 'id',
        'meta_tags': 'meta_tags',
        'publish_date': 'publish_date',
        'slug': 'slug',
        'title': 'title',
        'type': 'type',
        'url_slug': 'url_slug',
        'videos_count': 'videos_count'
    }

    def __init__(self, channel=None, description=None, first_video=None, followings_count=None, id=None, meta_tags=None, publish_date=None, slug=None, title=None, type=None, url_slug=None, videos_count=None):  # noqa: E501
        """LatestPlaylist - a model defined in Swagger"""  # noqa: E501
        self._channel = None
        self._description = None
        self._first_video = None
        self._followings_count = None
        self._id = None
        self._meta_tags = None
        self._publish_date = None
        self._slug = None
        self._title = None
        self._type = None
        self._url_slug = None
        self._videos_count = None
        self.discriminator = None
        if channel is not None:
            self.channel = channel
        if description is not None:
            self.description = description
        if first_video is not None:
            self.first_video = first_video
        if followings_count is not None:
            self.followings_count = followings_count
        if id is not None:
            self.id = id
        if meta_tags is not None:
            self.meta_tags = meta_tags
        if publish_date is not None:
            self.publish_date = publish_date
        if slug is not None:
            self.slug = slug
        if title is not None:
            self.title = title
        if type is not None:
            self.type = type
        if url_slug is not None:
            self.url_slug = url_slug
        if videos_count is not None:
            self.videos_count = videos_count

    @property
    def channel(self):
        """Gets the channel of this LatestPlaylist.  # noqa: E501


        :return: The channel of this LatestPlaylist.  # noqa: E501
        :rtype: Channel
        """
        return self._channel

    @channel.setter
    def channel(self, channel):
        """Sets the channel of this LatestPlaylist.


        :param channel: The channel of this LatestPlaylist.  # noqa: E501
        :type: Channel
        """

        self._channel = channel

    @property
    def description(self):
        """Gets the description of this LatestPlaylist.  # noqa: E501


        :return: The description of this LatestPlaylist.  # noqa: E501
        :rtype: object
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this LatestPlaylist.


        :param description: The description of this LatestPlaylist.  # noqa: E501
        :type: object
        """

        self._description = description

    @property
    def first_video(self):
        """Gets the first_video of this LatestPlaylist.  # noqa: E501


        :return: The first_video of this LatestPlaylist.  # noqa: E501
        :rtype: FirstVideo
        """
        return self._first_video

    @first_video.setter
    def first_video(self, first_video):
        """Sets the first_video of this LatestPlaylist.


        :param first_video: The first_video of this LatestPlaylist.  # noqa: E501
        :type: FirstVideo
        """

        self._first_video = first_video

    @property
    def followings_count(self):
        """Gets the followings_count of this LatestPlaylist.  # noqa: E501


        :return: The followings_count of this LatestPlaylist.  # noqa: E501
        :rtype: int
        """
        return self._followings_count

    @followings_count.setter
    def followings_count(self, followings_count):
        """Sets the followings_count of this LatestPlaylist.


        :param followings_count: The followings_count of this LatestPlaylist.  # noqa: E501
        :type: int
        """

        self._followings_count = followings_count

    @property
    def id(self):
        """Gets the id of this LatestPlaylist.  # noqa: E501


        :return: The id of this LatestPlaylist.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this LatestPlaylist.


        :param id: The id of this LatestPlaylist.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def meta_tags(self):
        """Gets the meta_tags of this LatestPlaylist.  # noqa: E501


        :return: The meta_tags of this LatestPlaylist.  # noqa: E501
        :rtype: object
        """
        return self._meta_tags

    @meta_tags.setter
    def meta_tags(self, meta_tags):
        """Sets the meta_tags of this LatestPlaylist.


        :param meta_tags: The meta_tags of this LatestPlaylist.  # noqa: E501
        :type: object
        """

        self._meta_tags = meta_tags

    @property
    def publish_date(self):
        """Gets the publish_date of this LatestPlaylist.  # noqa: E501


        :return: The publish_date of this LatestPlaylist.  # noqa: E501
        :rtype: datetime
        """
        return self._publish_date

    @publish_date.setter
    def publish_date(self, publish_date):
        """Sets the publish_date of this LatestPlaylist.


        :param publish_date: The publish_date of this LatestPlaylist.  # noqa: E501
        :type: datetime
        """

        self._publish_date = publish_date

    @property
    def slug(self):
        """Gets the slug of this LatestPlaylist.  # noqa: E501


        :return: The slug of this LatestPlaylist.  # noqa: E501
        :rtype: str
        """
        return self._slug

    @slug.setter
    def slug(self, slug):
        """Sets the slug of this LatestPlaylist.


        :param slug: The slug of this LatestPlaylist.  # noqa: E501
        :type: str
        """

        self._slug = slug

    @property
    def title(self):
        """Gets the title of this LatestPlaylist.  # noqa: E501


        :return: The title of this LatestPlaylist.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this LatestPlaylist.


        :param title: The title of this LatestPlaylist.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def type(self):
        """Gets the type of this LatestPlaylist.  # noqa: E501


        :return: The type of this LatestPlaylist.  # noqa: E501
        :rtype: int
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this LatestPlaylist.


        :param type: The type of this LatestPlaylist.  # noqa: E501
        :type: int
        """

        self._type = type

    @property
    def url_slug(self):
        """Gets the url_slug of this LatestPlaylist.  # noqa: E501


        :return: The url_slug of this LatestPlaylist.  # noqa: E501
        :rtype: str
        """
        return self._url_slug

    @url_slug.setter
    def url_slug(self, url_slug):
        """Sets the url_slug of this LatestPlaylist.


        :param url_slug: The url_slug of this LatestPlaylist.  # noqa: E501
        :type: str
        """

        self._url_slug = url_slug

    @property
    def videos_count(self):
        """Gets the videos_count of this LatestPlaylist.  # noqa: E501


        :return: The videos_count of this LatestPlaylist.  # noqa: E501
        :rtype: int
        """
        return self._videos_count

    @videos_count.setter
    def videos_count(self, videos_count):
        """Sets the videos_count of this LatestPlaylist.


        :param videos_count: The videos_count of this LatestPlaylist.  # noqa: E501
        :type: int
        """

        self._videos_count = videos_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LatestPlaylist, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LatestPlaylist):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
