# coding: utf-8

"""
    Pietsmiet.de API

    OpenAPI spec generated from HAR data for www.pietsmiet.de on 2024-09-03T03:22:16.459Z  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Link(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'active': 'bool',
        'label': 'AnyOfLinkLabel',
        'url': 'AnyOfLinkUrl'
    }

    attribute_map = {
        'active': 'active',
        'label': 'label',
        'url': 'url'
    }

    def __init__(self, active=None, label=None, url=None):  # noqa: E501
        """Link - a model defined in Swagger"""  # noqa: E501
        self._active = None
        self._label = None
        self._url = None
        self.discriminator = None
        if active is not None:
            self.active = active
        if label is not None:
            self.label = label
        if url is not None:
            self.url = url

    @property
    def active(self):
        """Gets the active of this Link.  # noqa: E501


        :return: The active of this Link.  # noqa: E501
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active):
        """Sets the active of this Link.


        :param active: The active of this Link.  # noqa: E501
        :type: bool
        """

        self._active = active

    @property
    def label(self):
        """Gets the label of this Link.  # noqa: E501


        :return: The label of this Link.  # noqa: E501
        :rtype: AnyOfLinkLabel
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this Link.


        :param label: The label of this Link.  # noqa: E501
        :type: AnyOfLinkLabel
        """

        self._label = label

    @property
    def url(self):
        """Gets the url of this Link.  # noqa: E501


        :return: The url of this Link.  # noqa: E501
        :rtype: AnyOfLinkUrl
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this Link.


        :param url: The url of this Link.  # noqa: E501
        :type: AnyOfLinkUrl
        """

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Link, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Link):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
