# coding: utf-8

"""
    Pietsmiet.de API

    OpenAPI spec generated from HAR data for www.pietsmiet.de on 2024-09-03T03:22:16.459Z  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SupportAddOn(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'max': 'int',
        'min': 'int',
        'title': 'str',
        'title_long': 'str'
    }

    attribute_map = {
        'id': 'id',
        'max': 'max',
        'min': 'min',
        'title': 'title',
        'title_long': 'title_long'
    }

    def __init__(self, id=None, max=None, min=None, title=None, title_long=None):  # noqa: E501
        """SupportAddOn - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._max = None
        self._min = None
        self._title = None
        self._title_long = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if max is not None:
            self.max = max
        if min is not None:
            self.min = min
        if title is not None:
            self.title = title
        if title_long is not None:
            self.title_long = title_long

    @property
    def id(self):
        """Gets the id of this SupportAddOn.  # noqa: E501


        :return: The id of this SupportAddOn.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SupportAddOn.


        :param id: The id of this SupportAddOn.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def max(self):
        """Gets the max of this SupportAddOn.  # noqa: E501


        :return: The max of this SupportAddOn.  # noqa: E501
        :rtype: int
        """
        return self._max

    @max.setter
    def max(self, max):
        """Sets the max of this SupportAddOn.


        :param max: The max of this SupportAddOn.  # noqa: E501
        :type: int
        """

        self._max = max

    @property
    def min(self):
        """Gets the min of this SupportAddOn.  # noqa: E501


        :return: The min of this SupportAddOn.  # noqa: E501
        :rtype: int
        """
        return self._min

    @min.setter
    def min(self, min):
        """Sets the min of this SupportAddOn.


        :param min: The min of this SupportAddOn.  # noqa: E501
        :type: int
        """

        self._min = min

    @property
    def title(self):
        """Gets the title of this SupportAddOn.  # noqa: E501


        :return: The title of this SupportAddOn.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this SupportAddOn.


        :param title: The title of this SupportAddOn.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def title_long(self):
        """Gets the title_long of this SupportAddOn.  # noqa: E501


        :return: The title_long of this SupportAddOn.  # noqa: E501
        :rtype: str
        """
        return self._title_long

    @title_long.setter
    def title_long(self, title_long):
        """Sets the title_long of this SupportAddOn.


        :param title_long: The title_long of this SupportAddOn.  # noqa: E501
        :type: str
        """

        self._title_long = title_long

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SupportAddOn, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SupportAddOn):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
