# coding: utf-8

"""
    Pietsmiet.de API

    OpenAPI spec generated from HAR data for www.pietsmiet.de on 2024-09-03T03:22:16.459Z  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class VideosClipsPostRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'perspective': 'object',
        'position': 'float',
        'video': 'int'
    }

    attribute_map = {
        'perspective': 'perspective',
        'position': 'position',
        'video': 'video'
    }

    def __init__(self, perspective=None, position=None, video=None):  # noqa: E501
        """VideosClipsPostRequest - a model defined in Swagger"""  # noqa: E501
        self._perspective = None
        self._position = None
        self._video = None
        self.discriminator = None
        if perspective is not None:
            self.perspective = perspective
        if position is not None:
            self.position = position
        if video is not None:
            self.video = video

    @property
    def perspective(self):
        """Gets the perspective of this VideosClipsPostRequest.  # noqa: E501


        :return: The perspective of this VideosClipsPostRequest.  # noqa: E501
        :rtype: object
        """
        return self._perspective

    @perspective.setter
    def perspective(self, perspective):
        """Sets the perspective of this VideosClipsPostRequest.


        :param perspective: The perspective of this VideosClipsPostRequest.  # noqa: E501
        :type: object
        """

        self._perspective = perspective

    @property
    def position(self):
        """Gets the position of this VideosClipsPostRequest.  # noqa: E501


        :return: The position of this VideosClipsPostRequest.  # noqa: E501
        :rtype: float
        """
        return self._position

    @position.setter
    def position(self, position):
        """Sets the position of this VideosClipsPostRequest.


        :param position: The position of this VideosClipsPostRequest.  # noqa: E501
        :type: float
        """

        self._position = position

    @property
    def video(self):
        """Gets the video of this VideosClipsPostRequest.  # noqa: E501


        :return: The video of this VideosClipsPostRequest.  # noqa: E501
        :rtype: int
        """
        return self._video

    @video.setter
    def video(self, video):
        """Sets the video of this VideosClipsPostRequest.


        :param video: The video of this VideosClipsPostRequest.  # noqa: E501
        :type: int
        """

        self._video = video

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VideosClipsPostRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VideosClipsPostRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
